// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1PEaSElYKmuZqUtHyFbVxXDVmcp6a_Yk',
    appId: '1:519734998543:web:52ef7a5fe7da48dd08557a',
    messagingSenderId: '519734998543',
    projectId: 'inventario-7b2d5',
    authDomain: 'inventario-7b2d5.firebaseapp.com',
    storageBucket: 'inventario-7b2d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBUWYRvT5jNWsXaIMsADdzHnaEJhkLkQE',
    appId: '1:519734998543:android:3a59f61799cfba3908557a',
    messagingSenderId: '519734998543',
    projectId: 'inventario-7b2d5',
    storageBucket: 'inventario-7b2d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLlMn3jl9nMy-wlkdoGOD3ywtZkVpZ3o0',
    appId: '1:519734998543:ios:431dd8cfc15d6c0108557a',
    messagingSenderId: '519734998543',
    projectId: 'inventario-7b2d5',
    storageBucket: 'inventario-7b2d5.firebasestorage.app',
    iosBundleId: 'com.example.flutterJueves',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLlMn3jl9nMy-wlkdoGOD3ywtZkVpZ3o0',
    appId: '1:519734998543:ios:431dd8cfc15d6c0108557a',
    messagingSenderId: '519734998543',
    projectId: 'inventario-7b2d5',
    storageBucket: 'inventario-7b2d5.firebasestorage.app',
    iosBundleId: 'com.example.flutterJueves',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1PEaSElYKmuZqUtHyFbVxXDVmcp6a_Yk',
    appId: '1:519734998543:web:2c5bfd6a2452628e08557a',
    messagingSenderId: '519734998543',
    projectId: 'inventario-7b2d5',
    authDomain: 'inventario-7b2d5.firebaseapp.com',
    storageBucket: 'inventario-7b2d5.firebasestorage.app',
  );
}
